coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 5%
    patch:
      default:
        target: 25%
        threshold: 5%

  ignore:
    - "src/**/*.stories.tsx"
    - "src/**/*.test.tsx"
    - "src/**/__tests__/**"
    - "src/app/globals.css"

comment:
  layout: "header, diff, files"
  behavior: default