import { render } from '@testing-library/react';
import RootLayout, { metadata } from '../layout';

// Mock the fonts
jest.mock('next/font/google', () => ({
  Geist: jest.fn(() => ({
    variable: '--font-geist-sans',
  })),
  Geist_Mono: jest.fn(() => ({
    variable: '--font-geist-mono',
  })),
}));

// Mock the AuthProvider
jest.mock('../context/AuthContext', () => ({
  AuthProvider: ({ children }: { children: React.ReactNode }) => (
    <div data-testid="auth-provider">{children}</div>
  ),
}));

// Mock CSS imports
jest.mock('../globals.css', () => ({}));

describe('RootLayout', () => {
  it('renders children within the layout structure', () => {
    const TestChild = () => <div data-testid="test-child">Test Content</div>;
    
    const { getByTestId } = render(
      <RootLayout>
        <TestChild />
      </RootLayout>
    );

    expect(getByTestId('test-child')).toBeInTheDocument();
    expect(getByTestId('test-child')).toHaveTextContent('Test Content');
  });

  it('wraps children with AuthProvider', () => {
    const TestChild = () => <div data-testid="test-child">Test Content</div>;
    
    const { getByTestId } = render(
      <RootLayout>
        <TestChild />
      </RootLayout>
    );

    const authProvider = getByTestId('auth-provider');
    const testChild = getByTestId('test-child');
    
    expect(authProvider).toBeInTheDocument();
    expect(authProvider).toContainElement(testChild);
  });

  it('renders html element with correct lang attribute', () => {
    const TestChild = () => <div>Test Content</div>;
    
    render(
      <RootLayout>
        <TestChild />
      </RootLayout>
    );

    const htmlElement = document.documentElement;
    expect(htmlElement).toHaveAttribute('lang', 'en');
  });

  it('applies correct CSS classes to body element', () => {
    const TestChild = () => <div>Test Content</div>;
    
    render(
      <RootLayout>
        <TestChild />
      </RootLayout>
    );

    const bodyElement = document.body;
    expect(bodyElement).toHaveClass('antialiased');
    expect(bodyElement.className).toContain('--font-geist-sans');
    expect(bodyElement.className).toContain('--font-geist-mono');
  });

  it('handles multiple children correctly', () => {
    const { getByTestId } = render(
      <RootLayout>
        <div data-testid="child-1">Child 1</div>
        <div data-testid="child-2">Child 2</div>
      </RootLayout>
    );

    expect(getByTestId('child-1')).toBeInTheDocument();
    expect(getByTestId('child-2')).toBeInTheDocument();
  });

  it('handles empty children', () => {
    const { getByTestId } = render(
      <RootLayout>
        {null}
      </RootLayout>
    );

    // Should still render AuthProvider even with null children
    expect(getByTestId('auth-provider')).toBeInTheDocument();
  });

  it('preserves the structure with nested components', () => {
    const NestedComponent = () => (
      <div data-testid="nested">
        <span data-testid="nested-child">Nested content</span>
      </div>
    );

    const { getByTestId } = render(
      <RootLayout>
        <NestedComponent />
      </RootLayout>
    );

    expect(getByTestId('nested')).toBeInTheDocument();
    expect(getByTestId('nested-child')).toBeInTheDocument();
    expect(getByTestId('auth-provider')).toContainElement(getByTestId('nested'));
  });
});

describe('metadata', () => {
  it('exports correct metadata object', () => {
    expect(metadata).toBeDefined();
    expect(metadata.title).toBe('Sports Stats Tracker');
    expect(metadata.description).toBe('Generated by create next app');
  });

  it('has the expected metadata structure', () => {
    expect(typeof metadata).toBe('object');
    expect(typeof metadata.title).toBe('string');
    expect(typeof metadata.description).toBe('string');
  });
});

describe('Font Configuration', () => {
  it('configures Geist font correctly', () => {
    const { Geist } = require('next/font/google');
    
    expect(Geist).toHaveBeenCalledWith({
      variable: '--font-geist-sans',
      subsets: ['latin'],
    });
  });

  it('configures Geist_Mono font correctly', () => {
    const { Geist_Mono } = require('next/font/google');
    
    expect(Geist_Mono).toHaveBeenCalledWith({
      variable: '--font-geist-mono',
      subsets: ['latin'],
    });
  });
});