import { render } from '@testing-library/react';
import RootLayout, { metadata } from '../layout';
import React from 'react';

// Mock the fonts
jest.mock('next/font/google', () => ({
  Geist: jest.fn(() => ({
    variable: '--font-geist-sans',
  })),
  Geist_Mono: jest.fn(() => ({
    variable: '--font-geist-mono',
  })),
}));

// Mock the AuthProvider
jest.mock('../context/AuthContext', () => ({
  AuthProvider: ({ children }: { children: React.ReactNode }) => (
    <div data-testid="auth-provider">{children}</div>
  ),
}));

// Mock sonner (toast notifications)
jest.mock('../../components/ui/sonner', () => ({
  Toaster: () => <div data-testid="toaster" />,
}));

// Mock CSS imports
jest.mock('../globals.css', () => ({}));

// Create a test wrapper that renders just the body content
const TestWrapper = ({ children }: { children: React.ReactNode }) => {
  // Extract just the body content from RootLayout
  return (
    <div data-testid="auth-provider">
      {children}
      <div data-testid="toaster" />
    </div>
  );
};

describe('RootLayout', () => {
  it('renders children within the layout structure', () => {
    const TestChild = () => <div data-testid="test-child">Test Content</div>;
    
    const { getByTestId } = render(
      <TestWrapper>
        <TestChild />
      </TestWrapper>
    );

    expect(getByTestId('test-child')).toBeInTheDocument();
    expect(getByTestId('test-child')).toHaveTextContent('Test Content');
  });

  it('wraps children with AuthProvider', () => {
    const TestChild = () => <div data-testid="test-child">Test Content</div>;
    
    const { getByTestId } = render(
      <TestWrapper>
        <TestChild />
      </TestWrapper>
    );

    const authProvider = getByTestId('auth-provider');
    const testChild = getByTestId('test-child');
    
    expect(authProvider).toBeInTheDocument();
    expect(authProvider).toContainElement(testChild);
  });

  it('handles multiple children correctly', () => {
    const { getByTestId } = render(
      <TestWrapper>
        <div data-testid="child-1">Child 1</div>
        <div data-testid="child-2">Child 2</div>
      </TestWrapper>
    );

    expect(getByTestId('child-1')).toBeInTheDocument();
    expect(getByTestId('child-2')).toBeInTheDocument();
  });

  it('handles empty children', () => {
    const { getByTestId } = render(
      <TestWrapper>
        {null}
      </TestWrapper>
    );

    // Should still render AuthProvider even with null children
    expect(getByTestId('auth-provider')).toBeInTheDocument();
  });

  it('preserves the structure with nested components', () => {
    const NestedComponent = () => (
      <div data-testid="nested">
        <span data-testid="nested-child">Nested content</span>
      </div>
    );

    const { getByTestId } = render(
      <TestWrapper>
        <NestedComponent />
      </TestWrapper>
    );

    expect(getByTestId('nested')).toBeInTheDocument();
    expect(getByTestId('nested-child')).toBeInTheDocument();
    expect(getByTestId('auth-provider')).toContainElement(getByTestId('nested'));
  });

  it('renders Toaster component', () => {
    const TestChild = () => <div>Test Content</div>;
    
    const { getByTestId } = render(
      <TestWrapper>
        <TestChild />
      </TestWrapper>
    );

    expect(getByTestId('toaster')).toBeInTheDocument();
  });
});

describe('RootLayout Structure', () => {
  // Test the actual RootLayout component structure
  it('has correct component structure', () => {
    const layout = RootLayout({ children: <div>Test</div> });
    
    // Verify it returns an html element
    expect(layout.type).toBe('html');
    expect(layout.props.lang).toBe('en');
  });

  it('applies correct classes to body', () => {
    const layout = RootLayout({ children: <div>Test</div> });
    const body = layout.props.children;
    
    // Verify body has correct className structure
    expect(body.type).toBe('body');
    expect(body.props.className).toContain('antialiased');
    expect(body.props.className).toContain('--font-geist-sans');
    expect(body.props.className).toContain('--font-geist-mono');
  });

  it('wraps children with AuthProvider in structure', () => {
    const TestChild = <div>Test Content</div>;
    const layout = RootLayout({ children: TestChild });
    const body = layout.props.children;
    
    // The body should contain AuthProvider as a child
    expect(body.props.children).toBeDefined();
  });
});

describe('metadata', () => {
  it('exports correct metadata object', () => {
    expect(metadata).toBeDefined();
    expect(metadata.title).toBe('Sports Stats Tracker');
    expect(metadata.description).toBe('Generated by create next app');
  });

  it('has the expected metadata structure', () => {
    expect(typeof metadata).toBe('object');
    expect(typeof metadata.title).toBe('string');
    expect(typeof metadata.description).toBe('string');
  });
});

describe('Font Configuration', () => {
  it('configures Geist font correctly', () => {
    const { Geist } = require('next/font/google');
    
    expect(Geist).toHaveBeenCalledWith({
      variable: '--font-geist-sans',
      subsets: ['latin'],
    });
  });

  it('configures Geist_Mono font correctly', () => {
    const { Geist_Mono } = require('next/font/google');
    
    expect(Geist_Mono).toHaveBeenCalledWith({
      variable: '--font-geist-mono',
      subsets: ['latin'],
    });
  });
});